.TH "DigimediaTek86/obj/Debug/.NETFramework,Version=v4.8.AssemblyAttributes.cs" 3 "Mardi 19 Octobre 2021" "Digimedia86" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DigimediaTek86/obj/Debug/.NETFramework,Version=v4.8.AssemblyAttributes.cs
.SH SYNOPSIS
.br
.PP
.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Digimedia86 à partir du code source\&.
