.TH "Répertoire de référence de DigimediaTek86/DataBase" 3 "Mardi 19 Octobre 2021" "Digimedia86" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Répertoire de référence de DigimediaTek86/DataBase
.SH SYNOPSIS
.br
.PP
.SS "Fichiers"

.in +1c
.ti -1c
.RI "fichier \fBprojetcnedDataSet\&.Designer\&.cs\fP"
.br
.in -1c
