.TH "Répertoire de référence de DigimediaTek86/modele" 3 "Mardi 19 Octobre 2021" "Digimedia86" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Répertoire de référence de DigimediaTek86/modele
.SH SYNOPSIS
.br
.PP
.SS "Fichiers"

.in +1c
.ti -1c
.RI "fichier \fBAbsence\&.cs\fP"
.br
.ti -1c
.RI "fichier \fBMotif\&.cs\fP"
.br
.ti -1c
.RI "fichier \fBPersonnel\&.cs\fP"
.br
.ti -1c
.RI "fichier \fBService\&.cs\fP"
.br
.in -1c
