.TH "Répertoire de référence de DigimediaTek86/obj" 3 "Mardi 19 Octobre 2021" "Digimedia86" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Répertoire de référence de DigimediaTek86/obj
.SH SYNOPSIS
.br
.PP
.SS "Répertoires"

.in +1c
.ti -1c
.RI "répertoire \fBDebug\fP"
.br
.ti -1c
.RI "répertoire \fBRelease\fP"
.br
.in -1c
