.TH "MediaTek.dal" 3 "Mardi 19 Octobre 2021" "Digimedia86" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MediaTek.dal
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAccesConnexionBdd\fP"
.br
.RI "Classe de gestion de la base de donnée "
.in -1c
.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Digimedia86 à partir du code source\&.
