.TH "MediaTek.DataBase.projetcnedDataSet.personnelRow" 3 "Mardi 19 Octobre 2021" "Digimedia86" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MediaTek.DataBase.projetcnedDataSet.personnelRow \- Represents strongly named DataRow class\&. /summary>  

.SH SYNOPSIS
.br
.PP
.PP
Est dérivée de global\&.SystemData\&.DataRow\&.
.SS "Fonctions membres publiques"

.in +1c
.ti -1c
.RI "bool \fBIsNOMNull\fP ()"
.br
.ti -1c
.RI "void \fBSetNOMNull\fP ()"
.br
.ti -1c
.RI "bool \fBIsPRENOMNull\fP ()"
.br
.ti -1c
.RI "void \fBSetPRENOMNull\fP ()"
.br
.ti -1c
.RI "bool \fBIsTELNull\fP ()"
.br
.ti -1c
.RI "void \fBSetTELNull\fP ()"
.br
.ti -1c
.RI "bool \fBIsMAILNull\fP ()"
.br
.ti -1c
.RI "void \fBSetMAILNull\fP ()"
.br
.in -1c
.SS "Propriétés"

.in +1c
.ti -1c
.RI "int \fBIDPERSONNEL\fP\fC [getset]\fP"
.br
.ti -1c
.RI "int \fBIDSERVICE\fP\fC [getset]\fP"
.br
.ti -1c
.RI "string \fBNOM\fP\fC [getset]\fP"
.br
.ti -1c
.RI "string \fBPRENOM\fP\fC [getset]\fP"
.br
.ti -1c
.RI "string \fBTEL\fP\fC [getset]\fP"
.br
.ti -1c
.RI "string \fBMAIL\fP\fC [getset]\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
Represents strongly named DataRow class\&. /summary> 

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Digimedia86 à partir du code source\&.
