.TH "MediaTek.DataBase.projetcnedDataSetTableAdapters" 3 "Mardi 19 Octobre 2021" "Digimedia86" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MediaTek.DataBase.projetcnedDataSetTableAdapters
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBabsenceTableAdapter\fP"
.br
.RI "Represents the connection and commands used to retrieve and save data\&. /summary> "
.ti -1c
.RI "class \fBmotifTableAdapter\fP"
.br
.RI "Represents the connection and commands used to retrieve and save data\&. /summary> "
.ti -1c
.RI "class \fBpersonnelTableAdapter\fP"
.br
.RI "Represents the connection and commands used to retrieve and save data\&. /summary> "
.ti -1c
.RI "class \fBresponsableTableAdapter\fP"
.br
.RI "Represents the connection and commands used to retrieve and save data\&. /summary> "
.ti -1c
.RI "class \fBserviceTableAdapter\fP"
.br
.RI "Represents the connection and commands used to retrieve and save data\&. /summary> "
.ti -1c
.RI "class \fBTableAdapterManager\fP"
.br
.RI "\fBTableAdapterManager\fP is used to coordinate TableAdapters in the dataset to enable Hierarchical Update scenarios /summary> "
.in -1c
.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Digimedia86 à partir du code source\&.
