.TH "DigimediaTek86/DataBase/projetcnedDataSet.Designer.cs" 3 "Mardi 19 Octobre 2021" "Digimedia86" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DigimediaTek86/DataBase/projetcnedDataSet.Designer.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBMediaTek\&.DataBase\&.projetcnedDataSet\fP"
.br
.RI "Represents a strongly typed in-memory cache of data\&. /summary> "
.ti -1c
.RI "class \fBMediaTek\&.DataBase\&.projetcnedDataSet\&.absenceDataTable\fP"
.br
.RI "Represents the strongly named DataTable class\&. /summary> "
.ti -1c
.RI "class \fBMediaTek\&.DataBase\&.projetcnedDataSet\&.motifDataTable\fP"
.br
.RI "Represents the strongly named DataTable class\&. /summary> "
.ti -1c
.RI "class \fBMediaTek\&.DataBase\&.projetcnedDataSet\&.personnelDataTable\fP"
.br
.RI "Represents the strongly named DataTable class\&. /summary> "
.ti -1c
.RI "class \fBMediaTek\&.DataBase\&.projetcnedDataSet\&.responsableDataTable\fP"
.br
.RI "Represents the strongly named DataTable class\&. /summary> "
.ti -1c
.RI "class \fBMediaTek\&.DataBase\&.projetcnedDataSet\&.serviceDataTable\fP"
.br
.RI "Represents the strongly named DataTable class\&. /summary> "
.ti -1c
.RI "class \fBMediaTek\&.DataBase\&.projetcnedDataSet\&.absenceRow\fP"
.br
.RI "Represents strongly named DataRow class\&. /summary> "
.ti -1c
.RI "class \fBMediaTek\&.DataBase\&.projetcnedDataSet\&.motifRow\fP"
.br
.RI "Represents strongly named DataRow class\&. /summary> "
.ti -1c
.RI "class \fBMediaTek\&.DataBase\&.projetcnedDataSet\&.personnelRow\fP"
.br
.RI "Represents strongly named DataRow class\&. /summary> "
.ti -1c
.RI "class \fBMediaTek\&.DataBase\&.projetcnedDataSet\&.responsableRow\fP"
.br
.RI "Represents strongly named DataRow class\&. /summary> "
.ti -1c
.RI "class \fBMediaTek\&.DataBase\&.projetcnedDataSet\&.serviceRow\fP"
.br
.RI "Represents strongly named DataRow class\&. /summary> "
.ti -1c
.RI "class \fBMediaTek\&.DataBase\&.projetcnedDataSet\&.absenceRowChangeEvent\fP"
.br
.RI "Row event argument class /summary> "
.ti -1c
.RI "class \fBMediaTek\&.DataBase\&.projetcnedDataSet\&.motifRowChangeEvent\fP"
.br
.RI "Row event argument class /summary> "
.ti -1c
.RI "class \fBMediaTek\&.DataBase\&.projetcnedDataSet\&.personnelRowChangeEvent\fP"
.br
.RI "Row event argument class /summary> "
.ti -1c
.RI "class \fBMediaTek\&.DataBase\&.projetcnedDataSet\&.responsableRowChangeEvent\fP"
.br
.RI "Row event argument class /summary> "
.ti -1c
.RI "class \fBMediaTek\&.DataBase\&.projetcnedDataSet\&.serviceRowChangeEvent\fP"
.br
.RI "Row event argument class /summary> "
.ti -1c
.RI "class \fBMediaTek\&.DataBase\&.projetcnedDataSetTableAdapters\&.absenceTableAdapter\fP"
.br
.RI "Represents the connection and commands used to retrieve and save data\&. /summary> "
.ti -1c
.RI "class \fBMediaTek\&.DataBase\&.projetcnedDataSetTableAdapters\&.motifTableAdapter\fP"
.br
.RI "Represents the connection and commands used to retrieve and save data\&. /summary> "
.ti -1c
.RI "class \fBMediaTek\&.DataBase\&.projetcnedDataSetTableAdapters\&.personnelTableAdapter\fP"
.br
.RI "Represents the connection and commands used to retrieve and save data\&. /summary> "
.ti -1c
.RI "class \fBMediaTek\&.DataBase\&.projetcnedDataSetTableAdapters\&.responsableTableAdapter\fP"
.br
.RI "Represents the connection and commands used to retrieve and save data\&. /summary> "
.ti -1c
.RI "class \fBMediaTek\&.DataBase\&.projetcnedDataSetTableAdapters\&.serviceTableAdapter\fP"
.br
.RI "Represents the connection and commands used to retrieve and save data\&. /summary> "
.ti -1c
.RI "class \fBMediaTek\&.DataBase\&.projetcnedDataSetTableAdapters\&.TableAdapterManager\fP"
.br
.RI "\fBTableAdapterManager\fP is used to coordinate TableAdapters in the dataset to enable Hierarchical Update scenarios /summary> "
.in -1c
.SS "Espaces de nommage"

.in +1c
.ti -1c
.RI "namespace \fBMediaTek\fP"
.br
.ti -1c
.RI "namespace \fBMediaTek\&.DataBase\fP"
.br
.ti -1c
.RI "namespace \fBMediaTek\&.DataBase\&.projetcnedDataSetTableAdapters\fP"
.br
.in -1c
.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Digimedia86 à partir du code source\&.
