.TH "Répertoire de référence de DigimediaTek86" 3 "Mardi 19 Octobre 2021" "Digimedia86" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Répertoire de référence de DigimediaTek86
.SH SYNOPSIS
.br
.PP
.SS "Répertoires"

.in +1c
.ti -1c
.RI "répertoire \fBconnexion\fP"
.br
.ti -1c
.RI "répertoire \fBcontroleur\fP"
.br
.ti -1c
.RI "répertoire \fBdal\fP"
.br
.ti -1c
.RI "répertoire \fBDataBase\fP"
.br
.ti -1c
.RI "répertoire \fBmodele\fP"
.br
.ti -1c
.RI "répertoire \fBobj\fP"
.br
.ti -1c
.RI "répertoire \fBProperties\fP"
.br
.ti -1c
.RI "répertoire \fBvue\fP"
.br
.in -1c
.SS "Fichiers"

.in +1c
.ti -1c
.RI "fichier \fBProgram\&.cs\fP"
.br
.in -1c
