.TH "MediaTek.DataBase.projetcnedDataSetTableAdapters.personnelTableAdapter" 3 "Mardi 19 Octobre 2021" "Digimedia86" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MediaTek.DataBase.projetcnedDataSetTableAdapters.personnelTableAdapter \- Represents the connection and commands used to retrieve and save data\&. /summary>  

.SH SYNOPSIS
.br
.PP
.PP
Est dérivée de global\&.SystemComponentModel\&.Component\&.
.SS "Fonctions membres publiques"

.in +1c
.ti -1c
.RI "virtual int \fBFill\fP (\fBprojetcnedDataSet\&.personnelDataTable\fP dataTable)"
.br
.ti -1c
.RI "virtual \fBprojetcnedDataSet\&.personnelDataTable\fP \fBGetData\fP ()"
.br
.ti -1c
.RI "virtual int \fBUpdate\fP (\fBprojetcnedDataSet\&.personnelDataTable\fP dataTable)"
.br
.ti -1c
.RI "virtual int \fBUpdate\fP (\fBprojetcnedDataSet\fP dataSet)"
.br
.ti -1c
.RI "virtual int \fBUpdate\fP (global::System\&.Data\&.DataRow dataRow)"
.br
.ti -1c
.RI "virtual int \fBUpdate\fP (global::System\&.Data\&.DataRow[] dataRows)"
.br
.ti -1c
.RI "virtual int \fBDelete\fP (int p1, int p2, string p4, string p6, string p8, string p10)"
.br
.ti -1c
.RI "virtual int \fBInsert\fP (int p1, string p2, string p3, string p4, string p5)"
.br
.ti -1c
.RI "virtual int \fBUpdate\fP (int p1, string p2, string p3, string p4, string p5, int p6, int p7, string p9, string p11, string p13, string p15)"
.br
.in -1c
.SS "Propriétés"

.in +1c
.ti -1c
.RI "global::MySql\&.Data\&.MySqlClient\&.MySqlCommand[] \fBCommandCollection\fP\fC [get]\fP"
.br
.ti -1c
.RI "bool \fBClearBeforeFill\fP\fC [getset]\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
Represents the connection and commands used to retrieve and save data\&. /summary> 

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Digimedia86 à partir du code source\&.
