.TH "MediaTek.vue.FrmConnexion" 3 "Mardi 19 Octobre 2021" "Digimedia86" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MediaTek.vue.FrmConnexion \- Fenêtre de connexion au programme  

.SH SYNOPSIS
.br
.PP
.PP
Est dérivée de Form\&.
.SS "Fonctions membres publiques"

.in +1c
.ti -1c
.RI "\fBFrmConnexion\fP (\fBControle\fP controle)"
.br
.RI "Constructeur Recupere l'instance du controleur et initialisation des composants de la Frame "
.in -1c
.SS "Fonctions membres protégées"

.in +1c
.ti -1c
.RI "override void \fBDispose\fP (bool disposing)"
.br
.RI "Nettoyage des ressources utilisées\&. "
.in -1c
.SH "Description détaillée"
.PP 
Fenêtre de connexion au programme 
.SH "Documentation des constructeurs et destructeur"
.PP 
.SS "MediaTek\&.vue\&.FrmConnexion\&.FrmConnexion (\fBControle\fP controle)"

.PP
Constructeur Recupere l'instance du controleur et initialisation des composants de la Frame 
.PP
\fBParamètres\fP
.RS 4
\fIcontrole\fP 
.RE
.PP

.SH "Documentation des fonctions membres"
.PP 
.SS "override void MediaTek\&.vue\&.FrmConnexion\&.Dispose (bool disposing)\fC [protected]\fP"

.PP
Nettoyage des ressources utilisées\&. 
.PP
\fBParamètres\fP
.RS 4
\fIdisposing\fP true si les ressources managées doivent être supprimées ; sinon, false\&.
.RE
.PP


.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Digimedia86 à partir du code source\&.
