.TH "MediaTek.DataBase.projetcnedDataSet.motifRow" 3 "Mardi 19 Octobre 2021" "Digimedia86" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MediaTek.DataBase.projetcnedDataSet.motifRow \- Represents strongly named DataRow class\&. /summary>  

.SH SYNOPSIS
.br
.PP
.PP
Est dérivée de global\&.SystemData\&.DataRow\&.
.SS "Fonctions membres publiques"

.in +1c
.ti -1c
.RI "bool \fBIsLIBELLENull\fP ()"
.br
.ti -1c
.RI "void \fBSetLIBELLENull\fP ()"
.br
.in -1c
.SS "Propriétés"

.in +1c
.ti -1c
.RI "int \fBIDMOTIF\fP\fC [getset]\fP"
.br
.ti -1c
.RI "string \fBLIBELLE\fP\fC [getset]\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
Represents strongly named DataRow class\&. /summary> 

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Digimedia86 à partir du code source\&.
