.TH "MediaTek.modele.Service" 3 "Mardi 19 Octobre 2021" "Digimedia86" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MediaTek.modele.Service \- Classe des services du personnel  

.SH SYNOPSIS
.br
.PP
.SS "Fonctions membres publiques"

.in +1c
.ti -1c
.RI "\fBService\fP (int idservice, string nom)"
.br
.RI "Constructeur de service et valorise ses propriétés "
.ti -1c
.RI "override string \fBToString\fP ()"
.br
.RI "Définir le nom du service n à afficher "
.in -1c
.SS "Propriétés"

.in +1c
.ti -1c
.RI "int \fBIdservice\fP\fC [get]\fP"
.br
.RI "Getter d'encapsulation d'idservice "
.ti -1c
.RI "string \fBNom\fP\fC [get]\fP"
.br
.RI "Getter d'encapsulation de nom "
.in -1c
.SH "Description détaillée"
.PP 
Classe des services du personnel 
.SH "Documentation des constructeurs et destructeur"
.PP 
.SS "MediaTek\&.modele\&.Service\&.Service (int idservice, string nom)"

.PP
Constructeur de service et valorise ses propriétés 
.PP
\fBParamètres\fP
.RS 4
\fIidservice\fP 
.br
\fInom\fP 
.RE
.PP

.SH "Documentation des fonctions membres"
.PP 
.SS "override string MediaTek\&.modele\&.Service\&.ToString ()"

.PP
Définir le nom du service n à afficher 
.PP
\fBRenvoie\fP
.RS 4
nom du service
.RE
.PP


.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Digimedia86 à partir du code source\&.
