.TH "MediaTek.modele.Personnel" 3 "Mardi 19 Octobre 2021" "Digimedia86" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MediaTek.modele.Personnel \- Classe représentant le personnel  

.SH SYNOPSIS
.br
.PP
.SS "Fonctions membres publiques"

.in +1c
.ti -1c
.RI "\fBPersonnel\fP (int idpersonnel, string nom, string prenom, string tel, string mail, int idservice, string service)"
.br
.RI "Constructeur de la classe \fBPersonnel\fP et valorise ses propriétes "
.in -1c
.SS "Propriétés"

.in +1c
.ti -1c
.RI "int \fBIdpersonnel\fP\fC [get]\fP"
.br
.RI "Getter sur idpersonnel "
.ti -1c
.RI "string \fBNom\fP\fC [get]\fP"
.br
.RI "Getter sur nom "
.ti -1c
.RI "string \fBPrenom\fP\fC [get]\fP"
.br
.RI "Getter sur prenom "
.ti -1c
.RI "string \fBTel\fP\fC [get]\fP"
.br
.RI "Getter sur tel "
.ti -1c
.RI "string \fBMail\fP\fC [get]\fP"
.br
.RI "Getter sur mail "
.ti -1c
.RI "int \fBIdservice\fP\fC [get]\fP"
.br
.RI "Getter sur idservice "
.ti -1c
.RI "string \fBService\fP\fC [get]\fP"
.br
.RI "Getter sur service "
.in -1c
.SH "Description détaillée"
.PP 
Classe représentant le personnel 
.SH "Documentation des constructeurs et destructeur"
.PP 
.SS "MediaTek\&.modele\&.Personnel\&.Personnel (int idpersonnel, string nom, string prenom, string tel, string mail, int idservice, string service)"

.PP
Constructeur de la classe \fBPersonnel\fP et valorise ses propriétes 
.PP
\fBParamètres\fP
.RS 4
\fIidpersonnel\fP 
.br
\fInom\fP 
.br
\fIprenom\fP 
.br
\fItel\fP 
.br
\fImail\fP 
.br
\fIidservice\fP 
.br
\fIservice\fP 
.RE
.PP


.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Digimedia86 à partir du code source\&.
